version: '2'

services:
  bitdb-btx:
    build:
      context: .
      dockerfile: "./containers/bitdb/Dockerfile.bitdb-btx"
    image: bitd-btx
    container_name: bitdb-btx
    working_dir: "/bitdb"
    command: bash -c "sleep 60 && npm start"
    restart: always
    ports:
      - "5555:30303"
    depends_on:
      - mongo
      - bitcored
    stdin_open: true
    tty: true

  bitcored:
    image: dalijolijo/bitcored-bitdb
    container_name: bitcored-bitdb
    command: -rpcuser=root -rpcpassword=bitcore
    restart: always
    ports:
      - "8556:8556"
      - "28556:28556"
    volumes:
      - ./containers/btx/data:/data 
    stdin_open: true
    tty: true

  mongo:
    image: mongo:latest
    container_name: mongo
    environment:
      -  'MONGODB_USER=user'
      -  'MONGODB_PASS=password!'
    volumes:
      - './containers/mongodb/data:/data/db'
    ports:
      - '27017:27017'
    command: mongod --smallfiles

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    links:
      - 'mongo:mongo'
    ports:
      - '8081:8081'
    environment:
      - 'ME_CONFIG_OPTIONS_EDITORTHEME=ambiance'
      - 'ME_CONFIG_BASICAUTH_USERNAME=user'
      - 'ME_CONFIG_BASICAUTH_PASSWORD=password!'

  # Grafana : http://localhost:3000/
  grafana:
    image: grafana/grafana:latest
    # build:
    #   context: .
    #   dockerfile: ./containers/grafana/Dockerfile
    environment:
      - GF_INSTALL_PLUGINS=crate-datasource,grafana-clock-panel,grafana-worldmap-panel
    ports:
      - '3000:3000'
    volumes:
      - './containers/grafana/data:/var/lib/grafana'
